version: "3"

volumes:
  postgres-data:
  redis-data:
  azurite-data:

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - 127.0.0.1:5000:443
    environment:
      - WEB_SERVER_URL=http://host.docker.internal:3000
      - WS_SERVER_URL=http://host.docker.internal:3001
    restart: always

  ws-server:
    build:
      context: .
      dockerfile: ./src/ws-server/Dockerfile
    container_name: ws-server
    ports:
      - 127.0.0.1:3001:3001
    depends_on:
      - postgres
      - redis
    profiles:
      - web
    links:
      - postgres
      - redis
    env_file: .env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    restart: always

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite
    volumes:
      - azurite-data:/data
    ports:
      - 10000:10000 # just blob storage
    restart: always
